// Generated by CoffeeScript 1.8.0
(function() {
  var IndexViewModel;

  IndexViewModel = (function() {
    function IndexViewModel() {
      this.title = ko.observable("Sasha Verma");
      this.menuItems = ko.observableArray([]);
    }

    IndexViewModel.prototype.addMenuItem = function(t, href) {
      return this.menuItems.push({
        name: t,
        url: href
      });
    };

    return IndexViewModel;

  })();

  $(document).ready(function() {
    var ivm;
    ivm = new IndexViewModel();
    ivm.addMenuItem('About', '#about');
    ivm.addMenuItem('Portfolio', '#portfolio');
    ivm.addMenuItem('Resume', '#resume');
    ivm.addMenuItem('Contact', '#contact');
    return ko.applyBindings(ivm);
  });

}).call(this);
